name: em-notebooks-environment

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - quadpy
  - scipy
  - matplotlib
  - ipywidgets>=0.6.0
  - mkl
  - pandas
  - pip:
    - pymatsolver
    - discretize
    - SimPEG
